/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.SenderTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sabrina
 */
public class RadioGUI extends javax.swing.JFrame {

    private SenderTableModel sm = new SenderTableModel();
    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
        this.setLocationRelativeTo(this);
        tbRadio.setModel(sm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miAdd = new javax.swing.JMenuItem();
        miHide = new javax.swing.JMenuItem();
        miShow = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRadio = new javax.swing.JTable();

        miAdd.setText("jMenuItem1");
        miAdd.setActionCommand("hinzufügen");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onHinzufuegen(evt);
            }
        });
        jPopupMenu1.add(miAdd);

        miHide.setText("jMenuItem2");
        miHide.setActionCommand("Band verstecken");
        miHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onVerstecken(evt);
            }
        });
        jPopupMenu1.add(miHide);

        miShow.setText("jMenuItem3");
        miShow.setActionCommand("Band anzeigen");
        miShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBandAnzeigen(evt);
            }
        });
        jPopupMenu1.add(miShow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setComponentPopupMenu(jPopupMenu1);

        tbRadio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbRadio.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tbRadio);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onHinzufuegen
        try
        {
            SenderDlg sdlg = new SenderDlg(this, true);
            sdlg.setVisible(true);
            
            if(sdlg.isOk())
            {
                sm.add(sdlg.getSender());
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_onHinzufuegen

    private void onVerstecken(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onVerstecken
        try
        {
            
//            taSender.removeColumn(taSender.getColumnModel().getColumn(2));
//            taSender.getModel().getValueAt(taSender.getSelectedRow(), 2);
            
//            TableColumnModel model = taSender.getColumnModel();
//            TableColumn col = model.getColumn(2);          
//            removed.add(col);
//            model.removeColumn(col);
            tbRadio.removeColumn(tbRadio.getColumnModel().getColumn(2));
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_onVerstecken

    private void onBandAnzeigen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBandAnzeigen
        try
        {
//            model.addColumn(col);
            
            tbRadio.addColumn(tbRadio.getColumn(2));
  
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_onBandAnzeigen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miHide;
    private javax.swing.JMenuItem miShow;
    private javax.swing.JTable tbRadio;
    // End of variables declaration//GEN-END:variables
}
