/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Sabrina
 */
public class SenderDlg extends javax.swing.JDialog {

    /**
     * Creates new form SenderDlg
     */
    public SenderDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSender = new javax.swing.JLabel();
        tfSender = new javax.swing.JTextField();
        lbFrequenz = new javax.swing.JLabel();
        tfFrequenz = new javax.swing.JTextField();
        lbBand = new javax.swing.JLabel();
        tfBand = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        lbSender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSender.setText("Sender:");
        getContentPane().add(lbSender);

        tfSender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfSender.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfSender);

        lbFrequenz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbFrequenz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFrequenz.setText("Frequenz:");
        getContentPane().add(lbFrequenz);

        tfFrequenz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfFrequenz.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfFrequenz);

        lbBand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBand.setText("Band:");
        getContentPane().add(lbBand);

        tfBand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfBand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfBand);

        btOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btOk.setText("OK");
        getContentPane().add(btOk);

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancel.setText("Cancel");
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenderDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenderDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenderDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenderDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SenderDlg dialog = new SenderDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbBand;
    private javax.swing.JLabel lbFrequenz;
    private javax.swing.JLabel lbSender;
    private javax.swing.JTextField tfBand;
    private javax.swing.JTextField tfFrequenz;
    private javax.swing.JTextField tfSender;
    // End of variables declaration//GEN-END:variables
}
